# Generated by Django 4.2.16 on 2026-05-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Admin must publish this assessment before students can see or submit it.",
            ),
        ),
    ]
