# Generated by Django 4.2.16 on 2026-05-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question as it would appear in the chat.', max_length=300)),
                ('keywords', models.CharField(help_text='Comma-separated trigger keywords. e.g. enroll,signup,register', max_length=500)),
                ('answer', models.TextField(help_text='Response the chatbot will show.')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher = checked first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-priority', 'question'],
            },
        ),
    ]
