# Generated by Django 4.2.16 on 2026-05-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.CharField(
                choices=[
                    ("enrollment", "Enrollment & Courses"),
                    ("account", "Account & Profile"),
                    ("payment", "Payment & Pricing"),
                    ("trainer", "Trainers & Approval"),
                    ("technical", "Technical Support"),
                    ("certificate", "Certificates"),
                    ("general", "General"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="faq",
            name="keywords",
            field=models.CharField(
                help_text="Comma-separated trigger words. e.g. enroll,join,register,course",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="priority",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Higher number = checked first when keywords match.",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=300),
        ),
    ]
